stages:
  - build
  - push

variables:
  DOCKER_IMAGE: harbor.52.79.177.100/library/fastapi-app
  TAG: latest

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin harbor.your-domain.com

build_and_push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$TAG .
    - docker push $DOCKER_IMAGE:$TAG